import React from 'react';
import { 
  MessageSquare, 
  Layout, 
  CreditCard, 
  Plus, 
  Clock, 
  Settings, 
  User, 
  Send, 
  Image as ImageIcon, 
  MoreHorizontal,
  ChevronRight,
  Eraser,
  Download,
  Wand2,
  PanelLeftClose,
  PanelLeftOpen,
  Trash2,
  LayoutGrid,
  Monitor,
  Smartphone,
  Square,
  Scan,
  Brush,
  RefreshCw
} from 'lucide-react';

export const Icons = {
  Chat: MessageSquare,
  Canvas: Layout,
  Billing: CreditCard,
  New: Plus,
  History: Clock,
  Settings: Settings,
  User: User,
  Send: Send,
  Image: ImageIcon,
  More: MoreHorizontal,
  ChevronRight: ChevronRight,
  Clear: Eraser,
  Download: Download,
  Magic: Wand2,
  SidebarClose: PanelLeftClose,
  SidebarOpen: PanelLeftOpen,
  Trash: Trash2,
  AutoLayout: Brush,
  Ratio: Scan,
  Square: Square,
  Landscape: Monitor,
  Portrait: Smartphone,
  Regenerate: RefreshCw
};